server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: file-storage
          uri: http://file-storage-service:8081
          predicates:
            - Path=/files/**
        - id: file-analysis
          uri: http://file-analysis-service:8082
          predicates:
            - Path=/analysis/**
