server:
  port: 8082

spring:
  application:
    name: file-analysis-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres   # ← localhost!
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

storage:
  base-url: http://localhost:8081                     # ← тоже localhost
